server:
   port: 8083
spring:
    applicacion:
       name: config-server
    cloud:
      config:
        server:
           git: 
              uri: https://github.com/10419/microservicios_2023.git
              search-paths: config-data
              username: 10419
              password: martinelmejor"=123
              default-label: main
   security: 
      user:
        name: root
        password: s3cr3t
